version: '3.8'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  api:
    build:
      context: .
      dockerfile: src/TLOM.API/Dockerfile
    ports:
      - "5170:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ConnectionStrings__Redis=redis:6379
      - ClientUrl=http://${EC2_HOST}
      - Jwt__Secret=${JWT_SECRET}

      - Jwt__Issuer=TLOM.API
      - Jwt__Audience=TLOM.Client
      - Google__ClientId=${GOOGLE_CLIENT_ID}
      - Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__FromEmail=${SMTP_FROM_EMAIL}
      - ExternalApis__Tmdb__BearerToken=${TMDB_BEARER_TOKEN}
      - ExternalApis__Tmdb__ApiKey=${TMDB_API_KEY}
      - ExternalApis__GoogleBooks__ApiKey=${GOOGLE_BOOKS_API_KEY}
      - ExternalApis__Spotify__ClientId=${SPOTIFY_CLIENT_ID}
      - ExternalApis__Spotify__ClientSecret=${SPOTIFY_CLIENT_SECRET}

  client:
    build:
      context: src/TLOM.Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
